apiVersion: v1
kind: Service
metadata:
  name: {{ include "robotics-fleet-management.fullname" . }}
  namespace: {{ .Values.namespace | default "paklog" }}
  labels:
    {{- include "robotics-fleet-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.managementPort }}
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
    {{- end }}
  selector:
    {{- include "robotics-fleet-management.selectorLabels" . | nindent 4 }}
